# Generated by Django 3.0.3 on 2021-02-05 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meme',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
