# Generated by Django 3.0.3 on 2021-06-04 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20210603_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='meme',
            name='image',
            field=models.ImageField(blank=True, upload_to='memes'),
        ),
    ]
