# Generated by Django 3.0.3 on 2021-06-04 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20210604_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meme',
            name='url',
        ),
    ]
